from langchain.tools import tool,ToolRuntime
from langchain.agents import create_agent
from src.utils import get_model
from src.schemas.schemas import UserContext
from src.utils import get_system_prompt
from src.access_control.permissions import ROLE_TOOLS
from src.access_control.permission_manager import get_allowed_tools
from langchain.agents.middleware import ModelCallLimitMiddleware
from src.memory.store import store
@tool("readonlyagents")
def get_read_only_agent(query: str , runtime: ToolRuntime[UserContext]):
    """
    Create and execute a role-based ReadOnly Agent.

    This tool is responsible for handling ALL user requests that retrieve
    information without modifying any data.

    The ReadOnly Agent dynamically selects the most appropriate read-only
    tool based on the user's request and the authenticated user's role.

    Typical requests include, but are not limited to:

    - View support tickets
    - Retrieve ticket details
    - Check ticket status
    - View ticket creation channels
    - Search tickets
    - Retrieve customer information
    - View product-related tickets
    - Any other read-only information

    Examples of supported requests:

    - Show my tickets
    - Show my open tickets
    - Show my ticket details
    - Show ticket 123
    - Show my channel
    - Show my channels
    - Show Email tickets
    - Show Phone tickets
    - Show the channel ritiksontakke1008@gmail.com
    - Show tickets for patricia@gmail.com
    - What is my ticket status?

    The ReadOnly Agent determines which read-only tool to invoke.
    It must not modify or delete any data.

    Access Control
    --------------
    - Customer:
    Can access only the read-only tools permitted for customers.

    - Manager:
    Can access only the read-only tools permitted for managers.

    - Admin:
    Can access all authorized read-only tools.

    Args:
        query (str):
            User's read-only request.

        runtime (ToolRuntime[UserContext]):
            Runtime context containing authenticated user information.

    Returns:
        str:
            Response generated by the appropriate read-only tool.

    Security:
    - Enforces Role-Based Access Control (RBAC).
    - Loads only tools authorized for the user's role.
    - Prevents unauthorized access.
    - Performs read-only operations only.
    """
    role = runtime.context.role
    tools = get_allowed_tools(role)
    if not tools:
        return f"Permission denied. No tools are available for role '{role}'."
    readonlyagent = create_agent(
        model=get_model(),
        store=store,
        tools=tools,
        middleware=[
        ModelCallLimitMiddleware(
            thread_limit=10,
            run_limit=5,
        ),
    ],
        context_schema=UserContext,
        system_prompt=get_system_prompt("cutomer_chatbot"),
    )

    result = readonlyagent.invoke({"messages": [{"role" :"user", "content":query}]} , context=runtime.context)
    return result["messages"][-1].content