from langchain.tools import tool,ToolRuntime
from langchain.agents import create_agent
from src.utils import get_model
from src.schemas.schemas import UserContext
from src.utils import get_system_prompt
from src.access_control.permissions import ROLE_TOOLS
from src.access_control.permission_manager import get_allowed_tools
from src.memory.store import store
@tool("readonlyagents")
def get_read_only_agent(query: str , runtime: ToolRuntime[UserContext]):
    """
    Create and execute a role-based read-only agent.

    This tool delegates user requests to a specialized ReadOnly Agent that
    has access only to read-only operations permitted for the authenticated
    user's role. The available tools are determined dynamically using the
    application's Role-Based Access Control (RBAC) system.

    The ReadOnly Agent can perform operations such as:
        - Search records
        - View support tickets
        - Check ticket status
        - Retrieve ticket details
        - View customer information
        - Access other read-only resources permitted for the user's role

    Access Control:
        - Admin:
            Can access all read-only resources in addition to any other
            permissions assigned to the role.
        - Other Roles:
            Can access only the read-only tools explicitly assigned to
            their role.
        - If no read-only tools are authorized for the current role,
            the agent returns a permission denied message.

    Args:
        query (str):
            The user's request to retrieve information.

        runtime (ToolRuntime[UserContext]):
            Runtime context containing the authenticated user's role and
            other contextual information.

    Returns:
        str:
            The response generated by the ReadOnly Agent, or a permission
            denied message if the role is not authorized.

    Security:
        - Enforces Role-Based Access Control (RBAC).
        - Restricts the agent to read-only operations.
        - Prevents unauthorized access to protected resources.
        - Dynamically loads only the tools permitted for the user's role.
    """

    role = runtime.context.role
    tools = get_allowed_tools(role)
    if not tools:
        return f"Permission denied. No tools are available for role '{role}'."
    readonlyagent = create_agent(
        model=get_model(),
        store=store,
        tools=tools,
        context_schema=UserContext,
        system_prompt=get_system_prompt("cutomer_chatbot"),
    )

    result = readonlyagent.invoke({"messages": [{"role" :"user", "content":query}]} , context=runtime.context)
    return result["messages"][-1].content