from langchain.tools import tool,ToolRuntime
from langchain.agents import create_agent
from src.utils import get_model
from src.schemas.schemas import UserContext
from src.utils import get_system_prompt
from src.access_control.permissions import ROLE_TOOLS
from src.access_control.permission_manager import get_allowed_tools

@tool("writeonlyagents")
def get_write_only_agent(query: str , runtime: ToolRuntime[UserContext]):
    """
    Create and execute a role-based agent with permissions determined by the
    authenticated user's role.

    The agent dynamically loads only the tools that the current user is
    authorized to access. Permissions are enforced using the application's
    Role-Based Access Control (RBAC) system.

    Role Permissions:
        - Admin:
            Full access to all available tools, including:
                * Create records
                * Read/Search records
                * Update records
                * Delete records
        - Other Roles:
            Access is limited to the tools explicitly assigned to their role.
            Any operation outside their permitted scope is denied.

    If the authenticated role has no authorized tools, the agent is not
    created and a permission denied message is returned.

    Args:
        query (str):
            The user's request to be processed.

        runtime (ToolRuntime[UserContext]):
            Runtime context containing the authenticated user's information,
            including their assigned role.

    Returns:
        str:
            The response generated by the role-specific agent or a permission
            denied message if the role has no authorized access.

    Security:
        - Enforces Role-Based Access Control (RBAC).
        - Prevents unauthorized access to restricted operations.
        - Ensures users can perform only the actions permitted by their role.
    """
    role = runtime.context.role
    tools = get_allowed_tools(role)
    if not tools:
        return f"Permission denied. No tools are available for role '{role}'."
    writeonlyagent = create_agent(
        model=get_model(),
        tools=tools,
        context_schema=UserContext,
        system_prompt=get_system_prompt("cutomer_chatbot"),
    )

    result = writeonlyagent.invoke({"messages": [{"role" :"user", "content":query}]} , context=runtime.context)
    return result["messages"][-1].content