from langchain.tools import tool,ToolRuntime
from langchain.agents import create_agent
from src.utils import get_model
from src.schemas.schemas import UserContext
from src.utils import get_system_prompt
from src.access_control.permissions import ROLE_TOOLS
from src.access_control.permission_manager import get_allowed_tools

@tool("writeonlyagents")
def get_write_only_agent(query: str , runtime: ToolRuntime[UserContext]):
    """
    Routes a user query to a role-restricted write-only agent.

    The agent is dynamically created using the tools permitted for the
    current user's role and executes the query within the provided user
    context. If the user's role has no authorized tools, a permission
    denial message is returned.

    Args:
        query: The user's request to be processed by the write-only agent.
        runtime: Tool runtime containing the authenticated UserContext,
            including the user's role and other contextual information.

    Returns:
        The final text response generated by the write-only agent, or a
        permission denial message if the user's role is not authorized to
        access any tools.
    """
    role = runtime.context.role
    tools = get_allowed_tools(role)
    if not tools:
        return f"Permission denied. No tools are available for role '{role}'."
    writeonlyagent = create_agent(
        model=get_model(),
        tools=tools,
        context_schema=UserContext,
        system_prompt=get_system_prompt("cutomer_chatbot"),
    )

    result = writeonlyagent.invoke({"messages": [{"role" :"user", "content":query}]} , context=runtime.context)
    return result["messages"][-1].content